In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
cars = pd.read_csv('cars.csv')

In [34]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [4]:
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [37]:
cars.value_counts('origin')

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [6]:
cars.origin.value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [7]:
cars.name.value_counts()

name
ford pinto             6
vw rabbit              5
ford maverick          5
toyota corolla         5
amc matador            5
                      ..
chevrolet monza 2+2    1
ford mustang ii        1
pontiac astro          1
amc pacer              1
chevrolet s-10         1
Name: count, Length: 300, dtype: int64

In [9]:
cars.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii
8,14.0,8,455.0,225.0,4425,10.0,70,usa,pontiac catalina
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl

In [11]:
cars.iloc[0,-1]

'chevrolet chevelle malibu'

In [12]:
len(cars.name)

398

In [13]:
cars.name.nunique()

300

In [19]:
cars[cars.name.duplicated() == True]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
29,27.0,4,97.0,88.0,2130,14.5,71,japan,datsun pl510
33,19.0,6,232.0,100.0,2634,13.0,71,usa,amc gremlin
35,17.0,6,250.0,100.0,3329,15.5,71,usa,chevrolet chevelle malibu
38,14.0,8,350.0,165.0,4209,12.0,71,usa,chevrolet impala
40,14.0,8,351.0,153.0,4154,13.5,71,usa,ford galaxie 500
...,...,...,...,...,...,...,...,...,...
363,22.4,6,231.0,110.0,3415,15.8,81,usa,buick century
372,27.0,4,151.0,90.0,2735,18.0,82,usa,pontiac phoenix
381,36.0,4,107.0,75.0,2205,14.5,82,japan,honda accord
382,34.0,4,108.0,70.0,2245,16.9,82,japan,toyota corolla
383,38.0,4,91.0,67.0,1965,15.0,82,japan,honda civic

In [20]:
cars.name.nunique()

300

In [24]:
cars.name.value_counts() > 1

name
ford pinto                               True
vw rabbit                                True
ford maverick                            True
toyota corolla                           True
amc matador                              True
toyota corona                            True
amc hornet                               True
chevrolet chevette                       True
amc gremlin                              True
peugeot 504                              True
chevrolet impala                         True
vw dasher                                True
dodge colt                               True
chevrolet vega                           True
chevrolet nova                           True
chevrolet citation                       True
chevrolet caprice classic                True
ford gran torino                         True
chevrolet chevelle malibu                True
honda civic                              True
plymouth duster                          True
ford galaxie 500                         True
plymouth fury iii                        True
pontiac catalina                         True
honda civic cvcc                         True
mazda 626                                True
chevrolet monte carlo landau             True
pontiac phoenix                          True
ford ltd                                 True
opel manta                               True
subaru dl                                True
vw rabbit custom                         True
chevrolet malibu                         True
honda accord                             True
plymouth reliant                         True
ford gran torino (sw)                    True
fiat 128                                 True
saab 99le                                True
audi 100ls                               True
datsun 210                               True
toyota mark ii                           True
buick skylark                            True
chevrolet chevelle malibu classic        True
mazda glc deluxe                         True
datsun 710                               True
oldsmobile cutlass salon brougham        True
amc concord                              True
dodge aspen                              True
subaru                                   True
buick century                            True
amc matador (sw)                         True
plymouth valiant                         True
opel 1900                                True
buick estate wagon (sw)                  True
datsun pl510                             True
ford country squire (sw)                 True
toyota corolla 1200                      True
datsun 200sx                            False
oldsmobile cutlass ciera (diesel)       False
ford granada l                          False
oldsmobile starfire sx                  False
datsun 200-sx                           False
audi 5000                               False
volvo 264gl                             False
saab 99gle                              False
peugeot 604sl                           False
chrysler lebaron medallion              False
vw scirocco                             False
honda accord lx                         False
toyota celica gt liftback               False
pontiac lemans v6                       False
mercury zephyr 6                        False
ford fairmont 4                         False
buick century limited                   False
amc concord dl 6                        False
dodge aspen 6                           False
ford ltd landau                         False
mercury grand marquis                   False
dodge st. regis                         False
datsun 310 gx                           False
honda civic (auto)                      False
chevrolet malibu classic (sw)           False
nissan stanza xe                        False
plymouth sapporo                        False
datsun 510                              False
dodge omni                              False
plymouth horizon miser                  False
ford ranger                             False
dodge rampage                           False
datsun 810                              False
vw pickup                               False
bmw 320i                                False
mazda rx-4                              False
vw rabbit custom diesel                 False
ford mustang gl                         False
ford fiesta                             False
chevrolet camaro                        False
datsun b210 gx                          False
dodge charger 2.2                       False
dodge diplomat                          False
mercury monarch ghia                    False
pontiac phoenix lj                      False
ford fairmont (auto)                    False
ford fairmont (man)                     False
plymouth volare                         False
toyota celica gt                        False
buick century special                   False
mercury zephyr                          False
amc concord d/l                         False
buick regal sport coupe (turbo)         False
ford futura                             False
dodge magnum xe                         False
mercury lynx l                          False
dodge colt hatchback custom             False
chrysler lebaron town @ country (sw)    False
toyota starlet                          False
chrysler lebaron salon                  False
mercedes-benz 240d                      False
honda civic 1500 gl                     False
ford granada gl                         False
oldsmobile cutlass ls                   False
renault lecar deluxe                    False
datsun 280-zx                           False
mazda rx-7 gs                           False
triumph tr7 coupe                       False
ford mustang cobra                      False
datsun 810 maxima                       False
dodge aries wagon (sw)                  False
plymouth champ                          False
honda prelude                           False
honda civic 1300                        False
toyota cressida                         False
datsun 210 mpg                          False
volvo diesel                            False
toyota tercel                           False
mazda glc 4                             False
plymouth horizon 4                      False
ford escort 4w                          False
ford escort 2h                          False
vw jetta                                False
renault 18i                             False
peugeot 505s turbo diesel               False
audi 5000s (diesel)                     False
vw dasher (diesel)                      False
vw rabbit c (diesel)                    False
mazda glc                               False
amc spirit dl                           False
mercedes-benz 300d                      False
mazda glc custom                        False
cadillac eldorado                       False
mazda glc custom l                      False
plymouth horizon                        False
vw rabbit l                             False
amc concord dl                          False
plymouth horizon tc3                    False
ford fairmont futura                    False
dodge aries se                          False
pontiac j2000 se hatchback              False
fiat strada custom                      False
buick skylark limited                   False
chevrolet cavalier 2-door               False
oldsmobile omega brougham               False
chevrolet cavalier wagon                False
toyota corolla tercel                   False
datsun 310                              False
ford fairmont                           False
audi 4000                               False
toyota corona liftback                  False
chevrolet cavalier                      False
datsun 510 hatchback                    False
ford mustang ii 2+2                     False
dodge colt m/m                          False
cadillac seville                        False
toyota corolla liftback                 False
vw 411 (sw)                             False
toyota corona hardtop                   False
dodge colt hardtop                      False
vw type 3                               False
ford pinto runabout                     False
amc ambassador sst                      False
mercury marquis                         False
buick lesabre custom                    False
oldsmobile delta 88 royale              False
chrysler newport royal                  False
mazda rx2 coupe                         False
chevrolet chevelle concours (sw)        False
plymouth satellite custom (sw)          False
volvo 145e (sw)                         False
peugeot 504 (sw)                        False
vw model 111                            False
renault 12 (sw)                         False
ford pinto (sw)                         False
datsun 510 (sw)                         False
toyota corona mark ii (sw)              False
dodge colt (sw)                         False
toyota corolla 1600 (sw)                False
buick century 350                       False
dodge coronet custom                    False
mercury marquis brougham                False
plymouth fury gran sedan                False
chrysler new yorker brougham            False
buick electra 225 custom                False
amc ambassador brougham                 False
plymouth cricket                        False
datsun 1200                             False
vw super beetle                         False
chevrolet c20                           False
plymouth satellite                      False
amc rebel sst                           False
ford torino                             False
amc ambassador dpl                      False
dodge challenger se                     False
plymouth 'cuda 340                      False
chevrolet monte carlo                   False
toyota corona mark ii                   False
vw 1131 deluxe sedan                    False
audi 100 ls                             False
saab 99e                                False
bmw 2002                                False
ford f250                               False
dodge d200                              False
fiat 124b                               False
ih 1200d                                False
chevrolet vega 2300                     False
plymouth satellite custom               False
ford torino 500                         False
pontiac catalina brougham               False
dodge monaco (sw)                       False
pontiac safari (sw)                     False
amc hornet sportabout (sw)              False
chevrolet vega (sw)                     False
pontiac firebird                        False
ford mustang                            False
mercury capri 2000                      False
peugeot 304                             False
chevrolet nova custom                   False
ford country                            False
pontiac sunbird coupe                   False
dodge d100                              False
dodge coronet brougham                  False
chevrolet woody                         False
dodge aspen se                          False
ford granada ghia                       False
pontiac ventura sj                      False
amc pacer d/l                           False
datsun b-210                            False
volvo 245                               False
plymouth volare premier v8              False
mercedes-benz 280s                      False
buick skylark 320                       False
chevrolet c10                           False
ford f108                               False
honda accord cvcc                       False
mercury capri ii                        False
buick opel isuzu deluxe                 False
renault 5 gtl                           False
plymouth arrow gs                       False
datsun f-10 hatchback                   False
oldsmobile cutlass supreme              False
dodge monaco brougham                   False
mercury cougar brougham                 False
chevrolet concours                      False
plymouth volare custom                  False
ford granada                            False
pontiac grand prix lj                   False
chrysler cordoba                        False
ford thunderbird                        False
renault 12tl                            False
fiat 131                                False
plymouth custom suburb                  False
buick century luxus (sw)                False
oldsmobile vista cruiser                False
toyota carina                           False
datsun 610                              False
mazda rx3                               False
mercury capri v6                        False
fiat 124 sport coupe                    False
chevrolet monte carlo s                 False
pontiac grand prix                      False
volvo 144ea                             False
dodge dart custom                       False
oldsmobile omega                        False
datsun b210                             False
plymouth satellite sebring              False
dodge coronet custom (sw)               False
volvo 244dl                             False
audi fox                                False
fiat 124 tc                             False
fiat x1.9                               False
plymouth valiant custom                 False
mercury monarch                         False
chevrolet bel air                       False
plymouth grand fury                     False
plymouth fury                           False
buick skyhawk                           False
chevrolet monza 2+2                     False
ford mustang ii                         False
pontiac astro                           False
amc pacer                               False
chevrolet s-10                          False
Name: count, dtype: bool

In [22]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [27]:
cars.describe(include = 'all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,300
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,usa,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,NaN,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,NaN,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,NaN,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,NaN,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,NaN,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,NaN,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,NaN,NaN

In [28]:
cars.horsepower.max()

230.0

In [29]:
import pandas as pd

In [30]:
cars = pd.read_csv('cars.csv')

In [33]:
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [1]:
import pandas as pd

In [2]:
temp = pd.read_csv('temp.csv')

In [5]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  35064 non-null  object
 1   LA        35062 non-null  float64
 2   NY        35064 non-null  float64
dtypes: float64(2), object(1)
memory usage: 821.9+ KB

In [9]:
temp.describe(include = 'all')

                   datetime            LA            NY
count                 35064  35062.000000  35064.000000
unique                35064           NaN           NaN
top     2013-01-01 00:00:00           NaN           NaN
freq                      1           NaN           NaN
mean                    NaN     17.486016     12.068269
std                     NaN      6.640666     10.466832
min                     NaN     -6.600000    -22.400000
25%                     NaN     12.900000      3.900000
50%                     NaN     17.200000     12.500000
75%                     NaN     21.900000     20.600000
max                     NaN     42.300000     37.100000

In [12]:
temp1 = pd.read_csv('temp.csv', parse_dates= ['datetime'], index_col= 'datetime')

In [14]:
temp1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 35064 entries, 2013-01-01 00:00:00 to 2016-12-31 23:00:00
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   LA      35062 non-null  float64
 1   NY      35064 non-null  float64
dtypes: float64(2)
memory usage: 821.8 KB

In [15]:
temp1.describe()

                 LA            NY
count  35062.000000  35064.000000
mean      17.486016     12.068269
std        6.640666     10.466832
min       -6.600000    -22.400000
25%       12.900000      3.900000
50%       17.200000     12.500000
75%       21.900000     20.600000
max       42.300000     37.100000

In [22]:
type(temp.iloc[0,1])

numpy.float64

In [23]:
temp1

                       LA   NY
datetime
2013-01-01 00:00:00  11.7 -1.1
2013-01-01 01:00:00  10.7 -1.7
2013-01-01 02:00:00   9.9 -2.0
2013-01-01 03:00:00   9.3 -2.1
2013-01-01 04:00:00   8.8 -2.3
...                   ...  ...
2016-12-31 19:00:00  13.5  4.6
2016-12-31 20:00:00  13.2  5.7
2016-12-31 21:00:00  12.8  5.8
2016-12-31 22:00:00  12.3  5.7
2016-12-31 23:00:00  11.9  5.5

[35064 rows x 2 columns]

In [26]:
temp1.index[0:10]

DatetimeIndex(['2013-01-01 00:00:00', '2013-01-01 01:00:00',
               '2013-01-01 02:00:00', '2013-01-01 03:00:00',
               '2013-01-01 04:00:00', '2013-01-01 05:00:00',
               '2013-01-01 06:00:00', '2013-01-01 07:00:00',
               '2013-01-01 08:00:00', '2013-01-01 09:00:00'],
              dtype='datetime64[ns]', name='datetime', freq=None)

In [27]:
temp

                  datetime    LA   NY
0      2013-01-01 00:00:00  11.7 -1.1
1      2013-01-01 01:00:00  10.7 -1.7
2      2013-01-01 02:00:00   9.9 -2.0
3      2013-01-01 03:00:00   9.3 -2.1
4      2013-01-01 04:00:00   8.8 -2.3
...                    ...   ...  ...
35059  2016-12-31 19:00:00  13.5  4.6
35060  2016-12-31 20:00:00  13.2  5.7
35061  2016-12-31 21:00:00  12.8  5.8
35062  2016-12-31 22:00:00  12.3  5.7
35063  2016-12-31 23:00:00  11.9  5.5

[35064 rows x 3 columns]

In [28]:
pd.to_datetime(temp.datetime)

0       2013-01-01 00:00:00
1       2013-01-01 01:00:00
2       2013-01-01 02:00:00
3       2013-01-01 03:00:00
4       2013-01-01 04:00:00
                ...
35059   2016-12-31 19:00:00
35060   2016-12-31 20:00:00
35061   2016-12-31 21:00:00
35062   2016-12-31 22:00:00
35063   2016-12-31 23:00:00
Name: datetime, Length: 35064, dtype: datetime64[ns]

In [29]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  35064 non-null  object
 1   LA        35062 non-null  float64
 2   NY        35064 non-null  float64
dtypes: float64(2), object(1)
memory usage: 821.9+ KB

In [33]:
temp = temp.set_index(pd.to_datetime(temp.datetime), drop = False)