In [1]:
import numpy as np
import pandas as pd

In [2]:
titanic = pd.read_csv('titanic.csv')

In [3]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [5]:
titanic.dtypes

survived      int64
pclass        int64
sex          object
age         float64
sibsp         int64
parch         int64
fare        float64
embarked     object
deck         object
dtype: object

In [6]:
titanic.count()

survived    891
pclass      891
sex         891
age         714
sibsp       891
parch       891
fare        891
embarked    889
deck        203
dtype: int64

In [7]:
titanic.survived.sum()

342

In [8]:
342/891

0.3838383838383838

In [11]:
titanic.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

In [12]:
titanic.head()
titanic.tail()
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      203 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [15]:
titanic.age.dtype

dtype('float64')

In [16]:
age = titanic.age

In [17]:
age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [18]:
type(age)

pandas.core.series.Series

In [19]:
age.dtype

dtype('float64')

In [20]:
import pandas as pd

In [39]:
titanic = pd.read_csv('titanic.csv')
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [22]:
titanic.head(5)

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [23]:
titanic.tail(5)

     survived  pclass     sex   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

In [24]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      203 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [27]:
titanic.describe(include = 'all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,203
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,7
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,C
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,59
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN

In [40]:
age = titanic.age.copy()

In [41]:
age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [32]:
age.dtype
type(age)

pandas.core.series.Series

In [33]:
age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [42]:
age.fillna(age.mean(), inplace = True)

In [35]:
age

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [43]:
titanic.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [44]:
len(titanic.age)

891

In [45]:
age.index()

TypeError: 'RangeIndex' object is not callable

In [46]:
age.index

RangeIndex(start=0, stop=891, step=1)

In [47]:
age.columns

AttributeError: 'Series' object has no attribute 'columns'

In [48]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

In [52]:
age.to_frame('hello')

         hello
0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
..         ...
886  27.000000
887  19.000000
888  29.699118
889  26.000000
890  32.000000

[891 rows x 1 columns]

In [50]:
age

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: age, Length: 891, dtype: float64

In [53]:
hello

NameError: name 'hello' is not defined

In [57]:
type(age.to_frame)

method

In [58]:
age.sum(skipna = True)

26461.91382352941

In [59]:
age.sum()

26461.91382352941

In [60]:
age.nunique()

89

In [62]:
age.unique()

array([22.        , 38.        , 26.        , 35.        , 29.69911765,
       54.        ,  2.        , 27.        , 14.        ,  4.        ,
       58.        , 20.        , 39.        , 55.        , 31.        ,
       34.        , 15.        , 28.        ,  8.        , 19.        ,
       40.        , 66.        , 42.        , 21.        , 18.        ,
        3.        ,  7.        , 49.        , 29.        , 65.        ,
       28.5       ,  5.        , 11.        , 45.        , 17.        ,
       32.        , 16.        , 25.        ,  0.83      , 30.        ,
       33.        , 23.        , 24.        , 46.        , 59.        ,
       71.        , 37.        , 47.        , 14.5       , 70.5       ,
       32.5       , 12.        ,  9.        , 36.5       , 51.        ,
       55.5       , 40.5       , 44.        ,  1.        , 61.        ,
       56.        , 50.        , 36.        , 45.5       , 20.5       ,
       62.        , 41.        , 52.        , 63.        , 23.5       ,
        0.92      , 43.        , 60.        , 10.        , 64.        ,
       13.        , 48.        ,  0.75      , 53.        , 57.        ,
       80.        , 70.        , 24.5       ,  6.        ,  0.67      ,
       30.5       ,  0.42      , 34.5       , 74.        ])

In [63]:
age.mean()

29.69911764705882

In [64]:
age.max()

80.0

In [69]:
age.value_counts(sort = True, ascending = False)

age
29.699118    177
24.000000     30
22.000000     27
18.000000     26
28.000000     25
            ...
36.500000      1
55.500000      1
0.920000       1
23.500000      1
74.000000      1
Name: count, Length: 89, dtype: int64

In [71]:
age.value_counts(sort = True, bins = 10000000)

(29.699113, 29.699121]    177
(24.0, 24.000008]          30
(21.999995, 22.000003]     27
(17.999994, 18.000002]     26
(29.999997, 30.000005]     25
                         ...
(26.947149, 26.947157]      0
(26.947157, 26.947165]      0
(26.947165, 26.947173]      0
(26.947173, 26.947181]      0
(40.21, 40.210008]          0
Name: count, Length: 10000000, dtype: int64

In [75]:
age.count()

891

In [76]:
age.value_counts()

age
29.699118    177
24.000000     30
22.000000     27
18.000000     26
28.000000     25
            ...
36.500000      1
55.500000      1
0.920000       1
23.500000      1
74.000000      1
Name: count, Length: 89, dtype: int64

In [77]:
age.count()

891

In [79]:
age.info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: age
Non-Null Count  Dtype
--------------  -----
891 non-null    float64
dtypes: float64(1)
memory usage: 7.1 KB

In [81]:
age.describe()

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: age, dtype: float64

In [82]:
summer = pd.read_csv('summer.csv')

In [83]:
summer

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [87]:
summer.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Athlete', 'Country', 'Gender',
       'Event', 'Medal'],
      dtype='object')

In [88]:
summer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31165 entries, 0 to 31164
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        31165 non-null  int64
 1   City        31165 non-null  object
 2   Sport       31165 non-null  object
 3   Discipline  31165 non-null  object
 4   Athlete     31165 non-null  object
 5   Country     31161 non-null  object
 6   Gender      31165 non-null  object
 7   Event       31165 non-null  object
 8   Medal       31165 non-null  object
dtypes: int64(1), object(8)
memory usage: 2.1+ MB

In [90]:
summer.describe(include = 'all')

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
count,31165.000000,31165,31165,31165,31165,31161,31165,31165,31165
unique,NaN,22,43,67,22762,147,2,666,3
top,NaN,London,Aquatics,Athletics,"PHELPS, Michael",USA,Men,Football,Gold
freq,NaN,3567,4170,3638,22,4585,22746,1497,10486
mean,1970.482785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,33.158416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1896.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1948.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1980.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
athlete = summer.Athlete

In [93]:
athlete.shape

(31165,)

In [94]:
athlete.size

31165

In [95]:
athlete.unique()

array(['HAJOS, Alfred', 'HERSCHMANN, Otto', 'DRIVAS, Dimitrios', ...,
       'TOTROV, Rustam', 'ALEKSANYAN, Artur', 'LIDBERG, Jimmy'],
      dtype=object)

In [98]:
athlete.nunique

<bound method IndexOpsMixin.nunique of 0                    HAJOS, Alfred
1                 HERSCHMANN, Otto
2                DRIVAS, Dimitrios
3               MALOKINIS, Ioannis
4               CHASAPIS, Spiridon
                   ...
31160           JANIKOWSKI, Damian
31161    REZAEI, Ghasem Gholamreza
31162               TOTROV, Rustam
31163            ALEKSANYAN, Artur
31164               LIDBERG, Jimmy
Name: Athlete, Length: 31165, dtype: object>

In [99]:
summer.iloc[0]

Year                    1896
City                  Athens
Sport               Aquatics
Discipline          Swimming
Athlete        HAJOS, Alfred
Country                  HUN
Gender                   Men
Event         100M Freestyle
Medal                   Gold
Name: 0, dtype: object

In [104]:
summer.iloc[100:,3:]

,Discipline,Athlete,Country,Gender,Event,Medal
100,Artistic G.,"FLATOW, Alfred",GER,Men,"Team, Parallel Bars",Gold
101,Artistic G.,"FLATOW, Gustav Felix",GER,Men,"Team, Parallel Bars",Gold
102,Artistic G.,"HILMAR, Georg",GER,Men,"Team, Parallel Bars",Gold
103,Artistic G.,"HOFMANN, Fritz",GER,Men,"Team, Parallel Bars",Gold
104,Artistic G.,"MANTEUFFEL, Fritz",GER,Men,"Team, Parallel Bars",Gold
...,...,...,...,...,...,...
31160,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [114]:
athlete = pd.read_csv('summer.csv', usecols = ['Athlete']).squeeze('columns')

In [115]:
athlete

0                    HAJOS, Alfred
1                 HERSCHMANN, Otto
2                DRIVAS, Dimitrios
3               MALOKINIS, Ioannis
4               CHASAPIS, Spiridon
                   ...
31160           JANIKOWSKI, Damian
31161    REZAEI, Ghasem Gholamreza
31162               TOTROV, Rustam
31163            ALEKSANYAN, Artur
31164               LIDBERG, Jimmy
Name: Athlete, Length: 31165, dtype: object

In [120]:
pd.DataFrame()

              Name  Age   City
0   Prateek Chawla   24  Delhi
10  Prateek Chawla   24  Delhi

In [130]:
test = pd.Series(summer.Athlete)

In [133]:
test

0                    HAJOS, Alfred
1                 HERSCHMANN, Otto
2                DRIVAS, Dimitrios
3               MALOKINIS, Ioannis
4               CHASAPIS, Spiridon
                   ...
31160           JANIKOWSKI, Damian
31161    REZAEI, Ghasem Gholamreza
31162               TOTROV, Rustam
31163            ALEKSANYAN, Artur
31164               LIDBERG, Jimmy
Name: Athlete, Length: 31165, dtype: object

In [132]:
summer.Athlete

0                    HAJOS, Alfred
1                 HERSCHMANN, Otto
2                DRIVAS, Dimitrios
3               MALOKINIS, Ioannis
4               CHASAPIS, Spiridon
                   ...
31160           JANIKOWSKI, Damian
31161    REZAEI, Ghasem Gholamreza
31162               TOTROV, Rustam
31163            ALEKSANYAN, Artur
31164               LIDBERG, Jimmy
Name: Athlete, Length: 31165, dtype: object

In [134]:
sales = pd.Series(np.arange(0,20,2))

In [135]:
sales

0     0
1     2
2     4
3     6
4     8
5    10
6    12
7    14
8    16
9    18
dtype: int32

In [141]:
dic = {"mon": 10, "Tues" : 20, "Wed":30}

In [146]:
test = pd.Series(dic,name = 'sales')

In [147]:
test

mon     10
Tues    20
Wed     30
Name: sales, dtype: int64

In [159]:
age = summer.Athlete
age

0                    HAJOS, Alfred
1                 HERSCHMANN, Otto
2                DRIVAS, Dimitrios
3               MALOKINIS, Ioannis
4               CHASAPIS, Spiridon
                   ...
31160           JANIKOWSKI, Damian
31161    REZAEI, Ghasem Gholamreza
31162               TOTROV, Rustam
31163            ALEKSANYAN, Artur
31164               LIDBERG, Jimmy
Name: Athlete, Length: 31165, dtype: object

In [165]:
age.iloc[-1]

'LIDBERG, Jimmy'

In [164]:
age.iloc["HERSCHMANN, Otto"]

TypeError: Cannot index by location index with a non-integer key

In [166]:
age

0                    HAJOS, Alfred
1                 HERSCHMANN, Otto
2                DRIVAS, Dimitrios
3               MALOKINIS, Ioannis
4               CHASAPIS, Spiridon
                   ...
31160           JANIKOWSKI, Damian
31161    REZAEI, Ghasem Gholamreza
31162               TOTROV, Rustam
31163            ALEKSANYAN, Artur
31164               LIDBERG, Jimmy
Name: Athlete, Length: 31165, dtype: object

In [170]:
summer.sort_values('Year',ascending = False)

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze
29885,2012,London,Boxing,Boxing,"NEVIN, John Joe",IRL,Men,56KG,Silver
29857,2012,London,Basketball,Basketball,"BISHOP, Abby",AUS,Women,Basketball,Bronze
29858,2012,London,Basketball,Basketball,"CAMBAGE, Elizabeth",AUS,Women,Basketball,Bronze
29859,2012,London,Basketball,Basketball,"HARROWER, Kristi",AUS,Women,Basketball,Bronze
...,...,...,...,...,...,...,...,...,...
101,1896,Athens,Gymnastics,Artistic G.,"FLATOW, Gustav Felix",GER,Men,"Team, Parallel Bars",Gold
100,1896,Athens,Gymnastics,Artistic G.,"FLATOW, Alfred",GER,Men,"Team, Parallel Bars",Gold
99,1896,Athens,Gymnastics,Artistic G.,"BÖCKER, Konrad",GER,Men,"Team, Parallel Bars",Gold
98,1896,Athens,Gymnastics,Artistic G.,"MITROPOULOS, Ioannis",GRE,Men,"Team, Parallel Bars",Bronze
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold

In [172]:
summer.sort_index(ascending = False)

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
...,...,...,...,...,...,...,...,...,...
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold

In [173]:
summer.set_index('Year')

,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
Year,,,,,,,,
1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...
2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [182]:
summer.iloc[2012:]

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
2012,1912,Stockholm,Aquatics,Water polo,"HANSSON, Pontus",SWE,Men,Water Polo,Silver
2013,1912,Stockholm,Aquatics,Water polo,"JULIN, Harald S.A.",SWE,Men,Water Polo,Silver
2014,1912,Stockholm,Aquatics,Water polo,"KUMFELDT, K. Torsten",SWE,Men,Water Polo,Silver
2015,1912,Stockholm,Athletics,Athletics,"STENROOS, Albin Oskar",FIN,Men,10000M,Bronze
2016,1912,Stockholm,Athletics,Athletics,"KOLEHMAINEN, Hannes",FIN,Men,10000M,Gold
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [185]:
sales.sort_values(ascending = False, na_position = 'last', inplace = True)

In [186]:
sales

9    18
8    16
7    14
6    12
5    10
4     8
3     6
2     4
1     2
0     0
dtype: int32

In [189]:
summer.sort_values('Athlete', inplace = True, na_position = 'last')

In [188]:
summer

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
651,1900,Paris,Tug of War,Tug of War,"AABYE, Edgar",ZZX,Men,Tug Of War,Gold
2849,1920,Antwerp,Aquatics,Swimming,"AALTONEN, Arvo Ossian",FIN,Men,200M Breaststroke,Bronze
2852,1920,Antwerp,Aquatics,Swimming,"AALTONEN, Arvo Ossian",FIN,Men,400M Breaststroke,Bronze
7773,1948,London,Gymnastics,Artistic G.,"AALTONEN, Paavo Johannes",FIN,Men,Vault,Gold
8563,1952,Helsinki,Gymnastics,Artistic G.,"AALTONEN, Paavo Johannes",FIN,Men,Team Competition,Bronze
...,...,...,...,...,...,...,...,...,...
596,1900,Paris,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army Rifle, 300M, 3 Positions",Bronze
608,1900,Paris,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army Rifle, 300M, Standing",Silver
621,1900,Paris,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Free Rifle, Team",Silver
603,1900,Paris,Shooting,Shooting,"ÖSTMO, Ole",NOR,Men,"Army Rifle, 300M, Prone",Bronze
8051,1952,Helsinki,Aquatics,Swimming,"ÖSTRAND, Per-Olof",SWE,Men,400M Freestyle,Bronze

In [197]:
summer.Year.nlargest(n = 1.5)

TypeError: 'float' object cannot be interpreted as an integer

In [199]:
sales.idxmax()

9

In [200]:
sales.idxmin()

0

In [201]:
summer.idxmax()

TypeError: '>' not supported between instances of 'float' and 'str'

In [202]:
titanic.idxmax()

TypeError: '>' not supported between instances of 'str' and 'float'

In [206]:
titanic.idxmax(numeric_only= True)

survived      1
pclass        0
age         630
sibsp       159
parch       678
fare        258
dtype: int64

In [207]:
titanic.survived.idxmax()

1

In [209]:
titanic.iloc[630]

survived       1
pclass         1
sex         male
age         80.0
sibsp          0
parch          0
fare        30.0
embarked       S
deck           A
Name: 630, dtype: object

In [210]:
import pandas as pd

In [211]:
summer = pd.read_csv('summer.csv',index_col  = 'Athlete')

In [216]:
summer.nlargest(n = 10, columns = 'Year')

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"BOUDIA, David",2012,London,Aquatics,Diving,USA,Men,10M Platform,Gold
"QIU, Bo",2012,London,Aquatics,Diving,CHN,Men,10M Platform,Silver
"DALEY, Thomas",2012,London,Aquatics,Diving,GBR,Men,10M Platform,Bronze
"CHEN, Ruolin",2012,London,Aquatics,Diving,CHN,Women,10M Platform,Gold
"BROBEN, Brittany",2012,London,Aquatics,Diving,AUS,Women,10M Platform,Silver
"PAMG, Pandelela Rinong",2012,London,Aquatics,Diving,MAS,Women,10M Platform,Bronze
"ZAKHAROV, Ilya",2012,London,Aquatics,Diving,RUS,Men,3M Springboard,Gold
"QIN, Kai",2012,London,Aquatics,Diving,CHN,Men,3M Springboard,Silver
"HE, Chong",2012,London,Aquatics,Diving,CHN,Men,3M Springboard,Bronze
"WU, Minxia",2012,London,Aquatics,Diving,CHN,Women,3M Springboard,Gold

In [217]:
summer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31165 entries, HAJOS, Alfred to LIDBERG, Jimmy
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        31165 non-null  int64
 1   City        31165 non-null  object
 2   Sport       31165 non-null  object
 3   Discipline  31165 non-null  object
 4   Country     31161 non-null  object
 5   Gender      31165 non-null  object
 6   Event       31165 non-null  object
 7   Medal       31165 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.1+ MB

In [219]:
summer.head()

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [220]:
summer.tail(10)

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"AHMADOV, Emin",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 74 KG,Bronze
"KAZAKEVIC, Aleksandr",2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
"KHUGAEV, Alan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
"EBRAHIM, Karam Mohamed Gaber",2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
"GAJIYEV, Danyal",2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [221]:
summer.columns

Index(['Year', 'City', 'Sport', 'Discipline', 'Country', 'Gender', 'Event',
       'Medal'],
      dtype='object')

In [222]:
summer.index

Index(['HAJOS, Alfred', 'HERSCHMANN, Otto', 'DRIVAS, Dimitrios',
       'MALOKINIS, Ioannis', 'CHASAPIS, Spiridon', 'CHOROPHAS, Efstathios',
       'HAJOS, Alfred', 'ANDREOU, Joannis', 'CHOROPHAS, Efstathios',
       'NEUMANN, Paul',
       ...
       'AHMADOV, Emin', 'KAZAKEVIC, Aleksandr', 'KHUGAEV, Alan',
       'EBRAHIM, Karam Mohamed Gaber', 'GAJIYEV, Danyal', 'JANIKOWSKI, Damian',
       'REZAEI, Ghasem Gholamreza', 'TOTROV, Rustam', 'ALEKSANYAN, Artur',
       'LIDBERG, Jimmy'],
      dtype='object', name='Athlete', length=31165)

In [223]:
summer.columns.to_list()

['Year', 'City', 'Sport', 'Discipline', 'Country', 'Gender', 'Event', 'Medal']

In [225]:
summer.index.is_unique

False

In [226]:
summer.axes

[Index(['HAJOS, Alfred', 'HERSCHMANN, Otto', 'DRIVAS, Dimitrios',
        'MALOKINIS, Ioannis', 'CHASAPIS, Spiridon', 'CHOROPHAS, Efstathios',
        'HAJOS, Alfred', 'ANDREOU, Joannis', 'CHOROPHAS, Efstathios',
        'NEUMANN, Paul',
        ...
        'AHMADOV, Emin', 'KAZAKEVIC, Aleksandr', 'KHUGAEV, Alan',
        'EBRAHIM, Karam Mohamed Gaber', 'GAJIYEV, Danyal', 'JANIKOWSKI, Damian',
        'REZAEI, Ghasem Gholamreza', 'TOTROV, Rustam', 'ALEKSANYAN, Artur',
        'LIDBERG, Jimmy'],
       dtype='object', name='Athlete', length=31165),
 Index(['Year', 'City', 'Sport', 'Discipline', 'Country', 'Gender', 'Event',
        'Medal'],
       dtype='object')]

In [227]:
import pandas as pd

In [228]:
list_1 = [1,2,3]

In [236]:
pd.Index(list_1)

Index([1, 2, 100], dtype='int64')

In [233]:
type(list_1)

list

In [234]:
list_1[2] = 100

In [240]:
index_1 = pd.Index(list_1, name = 'numbers')

In [241]:
index_1

Index([1, 2, 100], dtype='int64', name='numbers')

In [244]:
df = pd.DataFrame(index_1, columns = index_1, index = index_1)

In [245]:
df

numbers  1    2    100
numbers
1        NaN  NaN  NaN
2        NaN  NaN  NaN
100      NaN  NaN  NaN

In [246]:
list1 = [1,2,3,4,5]

In [247]:
list_1

[1, 2, 100]

In [248]:
list_1

[1, 2, 100]

In [250]:
pd.Series([34,35,21], index = 'index_1')

TypeError: Index(...) must be called with a collection of some kind, 'index_1' was passed

In [251]:
import pandas as pd

In [252]:
summer = pd.read_csv('summer.csv', index_col = 'Athlete')

In [253]:
summer.index

Index(['HAJOS, Alfred', 'HERSCHMANN, Otto', 'DRIVAS, Dimitrios',
       'MALOKINIS, Ioannis', 'CHASAPIS, Spiridon', 'CHOROPHAS, Efstathios',
       'HAJOS, Alfred', 'ANDREOU, Joannis', 'CHOROPHAS, Efstathios',
       'NEUMANN, Paul',
       ...
       'AHMADOV, Emin', 'KAZAKEVIC, Aleksandr', 'KHUGAEV, Alan',
       'EBRAHIM, Karam Mohamed Gaber', 'GAJIYEV, Danyal', 'JANIKOWSKI, Damian',
       'REZAEI, Ghasem Gholamreza', 'TOTROV, Rustam', 'ALEKSANYAN, Artur',
       'LIDBERG, Jimmy'],
      dtype='object', name='Athlete', length=31165)

In [257]:
summer.drop_index('HERSCHMANN, Otto', inplace = True)

AttributeError: 'DataFrame' object has no attribute 'drop_index'

In [258]:
summer.reset_index(drop = False, inplace = True)

In [259]:
summer

,Athlete,Year,City,Sport,Discipline,Country,Gender,Event,Medal
0,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
1,"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
2,"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
3,"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
4,"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
31161,"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
31162,"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
31163,"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
31164,"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [260]:
summer.set_index()

TypeError: DataFrame.set_index() missing 1 required positional argument: 'keys'

In [261]:
summer.index.size

31165

In [262]:
summer.index.len

AttributeError: 'RangeIndex' object has no attribute 'len'

In [263]:
len(summer.index)

31165

In [268]:
index_1 = [f"Medal No {i}" for i in range (1, len(summer.index) + 1)]

In [269]:
index_1

['Medal No 1',
 'Medal No 2',
 'Medal No 3',
 'Medal No 4',
 'Medal No 5',
 'Medal No 6',
 'Medal No 7',
 'Medal No 8',
 'Medal No 9',
 'Medal No 10',
 'Medal No 11',
 'Medal No 12',
 'Medal No 13',
 'Medal No 14',
 'Medal No 15',
 'Medal No 16',
 'Medal No 17',
 'Medal No 18',
 'Medal No 19',
 'Medal No 20',
 'Medal No 21',
 'Medal No 22',
 'Medal No 23',
 'Medal No 24',
 'Medal No 25',
 'Medal No 26',
 'Medal No 27',
 'Medal No 28',
 'Medal No 29',
 'Medal No 30',
 'Medal No 31',
 'Medal No 32',
 'Medal No 33',
 'Medal No 34',
 'Medal No 35',
 'Medal No 36',
 'Medal No 37',
 'Medal No 38',
 'Medal No 39',
 'Medal No 40',
 'Medal No 41',
 'Medal No 42',
 'Medal No 43',
 'Medal No 44',
 'Medal No 45',
 'Medal No 46',
 'Medal No 47',
 'Medal No 48',
 'Medal No 49',
 'Medal No 50',
 'Medal No 51',
 'Medal No 52',
 'Medal No 53',
 'Medal No 54',
 'Medal No 55',
 'Medal No 56',
 'Medal No 57',
 'Medal No 58',
 'Medal No 59',
 'Medal No 60',
 'Medal No 61',
 'Medal No 62',
 'Medal No 63',
 'Medal No 64',
 'Medal No 65',
 'Medal No 66',
 'Medal No 67',
 'Medal No 68',
 'Medal No 69',
 'Medal No 70',
 'Medal No 71',
 'Medal No 72',
 'Medal No 73',
 'Medal No 74',
 'Medal No 75',
 'Medal No 76',
 'Medal No 77',
 'Medal No 78',
 'Medal No 79',
 'Medal No 80',
 'Medal No 81',
 'Medal No 82',
 'Medal No 83',
 'Medal No 84',
 'Medal No 85',
 'Medal No 86',
 'Medal No 87',
 'Medal No 88',
 'Medal No 89',
 'Medal No 90',
 'Medal No 91',
 'Medal No 92',
 'Medal No 93',
 'Medal No 94',
 'Medal No 95',
 'Medal No 96',
 'Medal No 97',
 'Medal No 98',
 'Medal No 99',
 'Medal No 100',
 'Medal No 101',
 'Medal No 102',
 'Medal No 103',
 'Medal No 104',
 'Medal No 105',
 'Medal No 106',
 'Medal No 107',
 'Medal No 108',
 'Medal No 109',
 'Medal No 110',
 'Medal No 111',
 'Medal No 112',
 'Medal No 113',
 'Medal No 114',
 'Medal No 115',
 'Medal No 116',
 'Medal No 117',
 'Medal No 118',
 'Medal No 119',
 'Medal No 120',
 'Medal No 121',
 'Medal No 122',
 'Medal No 123',
 'Medal No 124',
 'Medal No 125',
 'Medal No 126',
 'Medal No 127',
 'Medal No 128',
 'Medal No 129',
 'Medal No 130',
 'Medal No 131',
 'Medal No 132',
 'Medal No 133',
 'Medal No 134',
 'Medal No 135',
 'Medal No 136',
 'Medal No 137',
 'Medal No 138',
 'Medal No 139',
 'Medal No 140',
 'Medal No 141',
 'Medal No 142',
 'Medal No 143',
 'Medal No 144',
 'Medal No 145',
 'Medal No 146',
 'Medal No 147',
 'Medal No 148',
 'Medal No 149',
 'Medal No 150',
 'Medal No 151',
 'Medal No 152',
 'Medal No 153',
 'Medal No 154',
 'Medal No 155',
 'Medal No 156',
 'Medal No 157',
 'Medal No 158',
 'Medal No 159',
 'Medal No 160',
 'Medal No 161',
 'Medal No 162',
 'Medal No 163',
 'Medal No 164',
 'Medal No 165',
 'Medal No 166',
 'Medal No 167',
 'Medal No 168',
 'Medal No 169',
 'Medal No 170',
 'Medal No 171',
 'Medal No 172',
 'Medal No 173',
 'Medal No 174',
 'Medal No 175',
 'Medal No 176',
 'Medal No 177',
 'Medal No 178',
 'Medal No 179',
 'Medal No 180',
 'Medal No 181',
 'Medal No 182',
 'Medal No 183',
 'Medal No 184',
 'Medal No 185',
 'Medal No 186',
 'Medal No 187',
 'Medal No 188',
 'Medal No 189',
 'Medal No 190',
 'Medal No 191',
 'Medal No 192',
 'Medal No 193',
 'Medal No 194',
 'Medal No 195',
 'Medal No 196',
 'Medal No 197',
 'Medal No 198',
 'Medal No 199',
 'Medal No 200',
 'Medal No 201',
 'Medal No 202',
 'Medal No 203',
 'Medal No 204',
 'Medal No 205',
 'Medal No 206',
 'Medal No 207',
 'Medal No 208',
 'Medal No 209',
 'Medal No 210',
 'Medal No 211',
 'Medal No 212',
 'Medal No 213',
 'Medal No 214',
 'Medal No 215',
 'Medal No 216',
 'Medal No 217',
 'Medal No 218',
 'Medal No 219',
 'Medal No 220',
 'Medal No 221',
 'Medal No 222',
 'Medal No 223',
 'Medal No 224',
 'Medal No 225',
 'Medal No 226',
 'Medal No 227',
 'Medal No 228',
 'Medal No 229',
 'Medal No 230',
 'Medal No 231',
 'Medal No 232',
 'Medal No 233',
 'Medal No 234',
 'Medal No 235',
 'Medal No 236',
 'Medal No 237',
 'Medal No 238',
 'Medal No 239',
 'Medal No 240',
 'Medal No 241',
 'Medal No 242',
 'Medal No 243',
 'Medal No 244',
 'Medal No 245',
 'Medal No 246',
 'Medal No 247',
 'Medal No 248',
 'Medal No 249',
 'Medal No 250',
 'Medal No 251',
 'Medal No 252',
 'Medal No 253',
 'Medal No 254',
 'Medal No 255',
 'Medal No 256',
 'Medal No 257',
 'Medal No 258',
 'Medal No 259',
 'Medal No 260',
 'Medal No 261',
 'Medal No 262',
 'Medal No 263',
 'Medal No 264',
 'Medal No 265',
 'Medal No 266',
 'Medal No 267',
 'Medal No 268',
 'Medal No 269',
 'Medal No 270',
 'Medal No 271',
 'Medal No 272',
 'Medal No 273',
 'Medal No 274',
 'Medal No 275',
 'Medal No 276',
 'Medal No 277',
 'Medal No 278',
 'Medal No 279',
 'Medal No 280',
 'Medal No 281',
 'Medal No 282',
 'Medal No 283',
 'Medal No 284',
 'Medal No 285',
 'Medal No 286',
 'Medal No 287',
 'Medal No 288',
 'Medal No 289',
 'Medal No 290',
 'Medal No 291',
 'Medal No 292',
 'Medal No 293',
 'Medal No 294',
 'Medal No 295',
 'Medal No 296',
 'Medal No 297',
 'Medal No 298',
 'Medal No 299',
 'Medal No 300',
 'Medal No 301',
 'Medal No 302',
 'Medal No 303',
 'Medal No 304',
 'Medal No 305',
 'Medal No 306',
 'Medal No 307',
 'Medal No 308',
 'Medal No 309',
 'Medal No 310',
 'Medal No 311',
 'Medal No 312',
 'Medal No 313',
 'Medal No 314',
 'Medal No 315',
 'Medal No 316',
 'Medal No 317',
 'Medal No 318',
 'Medal No 319',
 'Medal No 320',
 'Medal No 321',
 'Medal No 322',
 'Medal No 323',
 'Medal No 324',
 'Medal No 325',
 'Medal No 326',
 'Medal No 327',
 'Medal No 328',
 'Medal No 329',
 'Medal No 330',
 'Medal No 331',
 'Medal No 332',
 'Medal No 333',
 'Medal No 334',
 'Medal No 335',
 'Medal No 336',
 'Medal No 337',
 'Medal No 338',
 'Medal No 339',
 'Medal No 340',
 'Medal No 341',
 'Medal No 342',
 'Medal No 343',
 'Medal No 344',
 'Medal No 345',
 'Medal No 346',
 'Medal No 347',
 'Medal No 348',
 'Medal No 349',
 'Medal No 350',
 'Medal No 351',
 'Medal No 352',
 'Medal No 353',
 'Medal No 354',
 'Medal No 355',
 'Medal No 356',
 'Medal No 357',
 'Medal No 358',
 'Medal No 359',
 'Medal No 360',
 'Medal No 361',
 'Medal No 362',
 'Medal No 363',
 'Medal No 364',
 'Medal No 365',
 'Medal No 366',
 'Medal No 367',
 'Medal No 368',
 'Medal No 369',
 'Medal No 370',
 'Medal No 371',
 'Medal No 372',
 'Medal No 373',
 'Medal No 374',
 'Medal No 375',
 'Medal No 376',
 'Medal No 377',
 'Medal No 378',
 'Medal No 379',
 'Medal No 380',
 'Medal No 381',
 'Medal No 382',
 'Medal No 383',
 'Medal No 384',
 'Medal No 385',
 'Medal No 386',
 'Medal No 387',
 'Medal No 388',
 'Medal No 389',
 'Medal No 390',
 'Medal No 391',
 'Medal No 392',
 'Medal No 393',
 'Medal No 394',
 'Medal No 395',
 'Medal No 396',
 'Medal No 397',
 'Medal No 398',
 'Medal No 399',
 'Medal No 400',
 'Medal No 401',
 'Medal No 402',
 'Medal No 403',
 'Medal No 404',
 'Medal No 405',
 'Medal No 406',
 'Medal No 407',
 'Medal No 408',
 'Medal No 409',
 'Medal No 410',
 'Medal No 411',
 'Medal No 412',
 'Medal No 413',
 'Medal No 414',
 'Medal No 415',
 'Medal No 416',
 'Medal No 417',
 'Medal No 418',
 'Medal No 419',
 'Medal No 420',
 'Medal No 421',
 'Medal No 422',
 'Medal No 423',
 'Medal No 424',
 'Medal No 425',
 'Medal No 426',
 'Medal No 427',
 'Medal No 428',
 'Medal No 429',
 'Medal No 430',
 'Medal No 431',
 'Medal No 432',
 'Medal No 433',
 'Medal No 434',
 'Medal No 435',
 'Medal No 436',
 'Medal No 437',
 'Medal No 438',
 'Medal No 439',
 'Medal No 440',
 'Medal No 441',
 'Medal No 442',
 'Medal No 443',
 'Medal No 444',
 'Medal No 445',
 'Medal No 446',
 'Medal No 447',
 'Medal No 448',
 'Medal No 449',
 'Medal No 450',
 'Medal No 451',
 'Medal No 452',
 'Medal No 453',
 'Medal No 454',
 'Medal No 455',
 'Medal No 456',
 'Medal No 457',
 'Medal No 458',
 'Medal No 459',
 'Medal No 460',
 'Medal No 461',
 'Medal No 462',
 'Medal No 463',
 'Medal No 464',
 'Medal No 465',
 'Medal No 466',
 'Medal No 467',
 'Medal No 468',
 'Medal No 469',
 'Medal No 470',
 'Medal No 471',
 'Medal No 472',
 'Medal No 473',
 'Medal No 474',
 'Medal No 475',
 'Medal No 476',
 'Medal No 477',
 'Medal No 478',
 'Medal No 479',
 'Medal No 480',
 'Medal No 481',
 'Medal No 482',
 'Medal No 483',
 'Medal No 484',
 'Medal No 485',
 'Medal No 486',
 'Medal No 487',
 'Medal No 488',
 'Medal No 489',
 'Medal No 490',
 'Medal No 491',
 'Medal No 492',
 'Medal No 493',
 'Medal No 494',
 'Medal No 495',
 'Medal No 496',
 'Medal No 497',
 'Medal No 498',
 'Medal No 499',
 'Medal No 500',
 'Medal No 501',
 'Medal No 502',
 'Medal No 503',
 'Medal No 504',
 'Medal No 505',
 'Medal No 506',
 'Medal No 507',
 'Medal No 508',
 'Medal No 509',
 'Medal No 510',
 'Medal No 511',
 'Medal No 512',
 'Medal No 513',
 'Medal No 514',
 'Medal No 515',
 'Medal No 516',
 'Medal No 517',
 'Medal No 518',
 'Medal No 519',
 'Medal No 520',
 'Medal No 521',
 'Medal No 522',
 'Medal No 523',
 'Medal No 524',
 'Medal No 525',
 'Medal No 526',
 'Medal No 527',
 'Medal No 528',
 'Medal No 529',
 'Medal No 530',
 'Medal No 531',
 'Medal No 532',
 'Medal No 533',
 'Medal No 534',
 'Medal No 535',
 'Medal No 536',
 'Medal No 537',
 'Medal No 538',
 'Medal No 539',
 'Medal No 540',
 'Medal No 541',
 'Medal No 542',
 'Medal No 543',
 'Medal No 544',
 'Medal No 545',
 'Medal No 546',
 'Medal No 547',
 'Medal No 548',
 'Medal No 549',
 'Medal No 550',
 'Medal No 551',
 'Medal No 552',
 'Medal No 553',
 'Medal No 554',
 'Medal No 555',
 'Medal No 556',
 'Medal No 557',
 'Medal No 558',
 'Medal No 559',
 'Medal No 560',
 'Medal No 561',
 'Medal No 562',
 'Medal No 563',
 'Medal No 564',
 'Medal No 565',
 'Medal No 566',
 'Medal No 567',
 'Medal No 568',
 'Medal No 569',
 'Medal No 570',
 'Medal No 571',
 'Medal No 572',
 'Medal No 573',
 'Medal No 574',
 'Medal No 575',
 'Medal No 576',
 'Medal No 577',
 'Medal No 578',
 'Medal No 579',
 'Medal No 580',
 'Medal No 581',
 'Medal No 582',
 'Medal No 583',
 'Medal No 584',
 'Medal No 585',
 'Medal No 586',
 'Medal No 587',
 'Medal No 588',
 'Medal No 589',
 'Medal No 590',
 'Medal No 591',
 'Medal No 592',
 'Medal No 593',
 'Medal No 594',
 'Medal No 595',
 'Medal No 596',
 'Medal No 597',
 'Medal No 598',
 'Medal No 599',
 'Medal No 600',
 'Medal No 601',
 'Medal No 602',
 'Medal No 603',
 'Medal No 604',
 'Medal No 605',
 'Medal No 606',
 'Medal No 607',
 'Medal No 608',
 'Medal No 609',
 'Medal No 610',
 'Medal No 611',
 'Medal No 612',
 'Medal No 613',
 'Medal No 614',
 'Medal No 615',
 'Medal No 616',
 'Medal No 617',
 'Medal No 618',
 'Medal No 619',
 'Medal No 620',
 'Medal No 621',
 'Medal No 622',
 'Medal No 623',
 'Medal No 624',
 'Medal No 625',
 'Medal No 626',
 'Medal No 627',
 'Medal No 628',
 'Medal No 629',
 'Medal No 630',
 'Medal No 631',
 'Medal No 632',
 'Medal No 633',
 'Medal No 634',
 'Medal No 635',
 'Medal No 636',
 'Medal No 637',
 'Medal No 638',
 'Medal No 639',
 'Medal No 640',
 'Medal No 641',
 'Medal No 642',
 'Medal No 643',
 'Medal No 644',
 'Medal No 645',
 'Medal No 646',
 'Medal No 647',
 'Medal No 648',
 'Medal No 649',
 'Medal No 650',
 'Medal No 651',
 'Medal No 652',
 'Medal No 653',
 'Medal No 654',
 'Medal No 655',
 'Medal No 656',
 'Medal No 657',
 'Medal No 658',
 'Medal No 659',
 'Medal No 660',
 'Medal No 661',
 'Medal No 662',
 'Medal No 663',
 'Medal No 664',
 'Medal No 665',
 'Medal No 666',
 'Medal No 667',
 'Medal No 668',
 'Medal No 669',
 'Medal No 670',
 'Medal No 671',
 'Medal No 672',
 'Medal No 673',
 'Medal No 674',
 'Medal No 675',
 'Medal No 676',
 'Medal No 677',
 'Medal No 678',
 'Medal No 679',
 'Medal No 680',
 'Medal No 681',
 'Medal No 682',
 'Medal No 683',
 'Medal No 684',
 'Medal No 685',
 'Medal No 686',
 'Medal No 687',
 'Medal No 688',
 'Medal No 689',
 'Medal No 690',
 'Medal No 691',
 'Medal No 692',
 'Medal No 693',
 'Medal No 694',
 'Medal No 695',
 'Medal No 696',
 'Medal No 697',
 'Medal No 698',
 'Medal No 699',
 'Medal No 700',
 'Medal No 701',
 'Medal No 702',
 'Medal No 703',
 'Medal No 704',
 'Medal No 705',
 'Medal No 706',
 'Medal No 707',
 'Medal No 708',
 'Medal No 709',
 'Medal No 710',
 'Medal No 711',
 'Medal No 712',
 'Medal No 713',
 'Medal No 714',
 'Medal No 715',
 'Medal No 716',
 'Medal No 717',
 'Medal No 718',
 'Medal No 719',
 'Medal No 720',
 'Medal No 721',
 'Medal No 722',
 'Medal No 723',
 'Medal No 724',
 'Medal No 725',
 'Medal No 726',
 'Medal No 727',
 'Medal No 728',
 'Medal No 729',
 'Medal No 730',
 'Medal No 731',
 'Medal No 732',
 'Medal No 733',
 'Medal No 734',
 'Medal No 735',
 'Medal No 736',
 'Medal No 737',
 'Medal No 738',
 'Medal No 739',
 'Medal No 740',
 'Medal No 741',
 'Medal No 742',
 'Medal No 743',
 'Medal No 744',
 'Medal No 745',
 'Medal No 746',
 'Medal No 747',
 'Medal No 748',
 'Medal No 749',
 'Medal No 750',
 'Medal No 751',
 'Medal No 752',
 'Medal No 753',
 'Medal No 754',
 'Medal No 755',
 'Medal No 756',
 'Medal No 757',
 'Medal No 758',
 'Medal No 759',
 'Medal No 760',
 'Medal No 761',
 'Medal No 762',
 'Medal No 763',
 'Medal No 764',
 'Medal No 765',
 'Medal No 766',
 'Medal No 767',
 'Medal No 768',
 'Medal No 769',
 'Medal No 770',
 'Medal No 771',
 'Medal No 772',
 'Medal No 773',
 'Medal No 774',
 'Medal No 775',
 'Medal No 776',
 'Medal No 777',
 'Medal No 778',
 'Medal No 779',
 'Medal No 780',
 'Medal No 781',
 'Medal No 782',
 'Medal No 783',
 'Medal No 784',
 'Medal No 785',
 'Medal No 786',
 'Medal No 787',
 'Medal No 788',
 'Medal No 789',
 'Medal No 790',
 'Medal No 791',
 'Medal No 792',
 'Medal No 793',
 'Medal No 794',
 'Medal No 795',
 'Medal No 796',
 'Medal No 797',
 'Medal No 798',
 'Medal No 799',
 'Medal No 800',
 'Medal No 801',
 'Medal No 802',
 'Medal No 803',
 'Medal No 804',
 'Medal No 805',
 'Medal No 806',
 'Medal No 807',
 'Medal No 808',
 'Medal No 809',
 'Medal No 810',
 'Medal No 811',
 'Medal No 812',
 'Medal No 813',
 'Medal No 814',
 'Medal No 815',
 'Medal No 816',
 'Medal No 817',
 'Medal No 818',
 'Medal No 819',
 'Medal No 820',
 'Medal No 821',
 'Medal No 822',
 'Medal No 823',
 'Medal No 824',
 'Medal No 825',
 'Medal No 826',
 'Medal No 827',
 'Medal No 828',
 'Medal No 829',
 'Medal No 830',
 'Medal No 831',
 'Medal No 832',
 'Medal No 833',
 'Medal No 834',
 'Medal No 835',
 'Medal No 836',
 'Medal No 837',
 'Medal No 838',
 'Medal No 839',
 'Medal No 840',
 'Medal No 841',
 'Medal No 842',
 'Medal No 843',
 'Medal No 844',
 'Medal No 845',
 'Medal No 846',
 'Medal No 847',
 'Medal No 848',
 'Medal No 849',
 'Medal No 850',
 'Medal No 851',
 'Medal No 852',
 'Medal No 853',
 'Medal No 854',
 'Medal No 855',
 'Medal No 856',
 'Medal No 857',
 'Medal No 858',
 'Medal No 859',
 'Medal No 860',
 'Medal No 861',
 'Medal No 862',
 'Medal No 863',
 'Medal No 864',
 'Medal No 865',
 'Medal No 866',
 'Medal No 867',
 'Medal No 868',
 'Medal No 869',
 'Medal No 870',
 'Medal No 871',
 'Medal No 872',
 'Medal No 873',
 'Medal No 874',
 'Medal No 875',
 'Medal No 876',
 'Medal No 877',
 'Medal No 878',
 'Medal No 879',
 'Medal No 880',
 'Medal No 881',
 'Medal No 882',
 'Medal No 883',
 'Medal No 884',
 'Medal No 885',
 'Medal No 886',
 'Medal No 887',
 'Medal No 888',
 'Medal No 889',
 'Medal No 890',
 'Medal No 891',
 'Medal No 892',
 'Medal No 893',
 'Medal No 894',
 'Medal No 895',
 'Medal No 896',
 'Medal No 897',
 'Medal No 898',
 'Medal No 899',
 'Medal No 900',
 'Medal No 901',
 'Medal No 902',
 'Medal No 903',
 'Medal No 904',
 'Medal No 905',
 'Medal No 906',
 'Medal No 907',
 'Medal No 908',
 'Medal No 909',
 'Medal No 910',
 'Medal No 911',
 'Medal No 912',
 'Medal No 913',
 'Medal No 914',
 'Medal No 915',
 'Medal No 916',
 'Medal No 917',
 'Medal No 918',
 'Medal No 919',
 'Medal No 920',
 'Medal No 921',
 'Medal No 922',
 'Medal No 923',
 'Medal No 924',
 'Medal No 925',
 'Medal No 926',
 'Medal No 927',
 'Medal No 928',
 'Medal No 929',
 'Medal No 930',
 'Medal No 931',
 'Medal No 932',
 'Medal No 933',
 'Medal No 934',
 'Medal No 935',
 'Medal No 936',
 'Medal No 937',
 'Medal No 938',
 'Medal No 939',
 'Medal No 940',
 'Medal No 941',
 'Medal No 942',
 'Medal No 943',
 'Medal No 944',
 'Medal No 945',
 'Medal No 946',
 'Medal No 947',
 'Medal No 948',
 'Medal No 949',
 'Medal No 950',
 'Medal No 951',
 'Medal No 952',
 'Medal No 953',
 'Medal No 954',
 'Medal No 955',
 'Medal No 956',
 'Medal No 957',
 'Medal No 958',
 'Medal No 959',
 'Medal No 960',
 'Medal No 961',
 'Medal No 962',
 'Medal No 963',
 'Medal No 964',
 'Medal No 965',
 'Medal No 966',
 'Medal No 967',
 'Medal No 968',
 'Medal No 969',
 'Medal No 970',
 'Medal No 971',
 'Medal No 972',
 'Medal No 973',
 'Medal No 974',
 'Medal No 975',
 'Medal No 976',
 'Medal No 977',
 'Medal No 978',
 'Medal No 979',
 'Medal No 980',
 'Medal No 981',
 'Medal No 982',
 'Medal No 983',
 'Medal No 984',
 'Medal No 985',
 'Medal No 986',
 'Medal No 987',
 'Medal No 988',
 'Medal No 989',
 'Medal No 990',
 'Medal No 991',
 'Medal No 992',
 'Medal No 993',
 'Medal No 994',
 'Medal No 995',
 'Medal No 996',
 'Medal No 997',
 'Medal No 998',
 'Medal No 999',
 'Medal No 1000',
 ...]

In [274]:
summer.reset_index(index_1, drop = True, inplace = True)

KeyError: 'Requested level (Medal No 1) does not match index name (None)'

In [275]:
index_1 =

,Athlete,Year,City,Sport,Discipline,Country,Gender,Event,Medal
0,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
1,"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
2,"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
3,"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
4,"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
31161,"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
31162,"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
31163,"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
31164,"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [276]:
summer.index = index_1

In [277]:
summer.head()

,Athlete,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Medal No 1,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
Medal No 2,"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
Medal No 3,"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
Medal No 4,"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
Medal No 5,"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [278]:
summer.index.name = 'Medal No'

In [281]:
summer.set_index('Medal No', inplace = True)

KeyError: "None of ['Medal No'] are in the columns"

In [282]:
summer

,Athlete,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Medal No,,,,,,,,,
Medal No 1,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
Medal No 2,"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
Medal No 3,"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
Medal No 4,"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
Medal No 5,"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
Medal No 31161,"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
Medal No 31162,"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
Medal No 31163,"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
Medal No 31164,"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
Medal No 31165,"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [285]:
summer.reset_index(inplace = True)

In [286]:
summer.set_index('Medal No', drop = True, inplace = True)

In [287]:
summer

,Athlete,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Medal No,,,,,,,,,
Medal No 1,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
Medal No 2,"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
Medal No 3,"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
Medal No 4,"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
Medal No 5,"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
Medal No 31161,"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
Medal No 31162,"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
Medal No 31163,"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
Medal No 31164,"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
Medal No 31165,"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [291]:
summer.columns = summer.columns.str.replace(' ','_')

In [300]:
summer.Country.name('g g',inplace = True)

TypeError: 'str' object is not callable

In [297]:
summer

,Athlete,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Medal No,,,,,,,,,
Medal No 1,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
Medal No 2,"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
Medal No 3,"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
Medal No 4,"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
Medal No 5,"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
Medal No 31161,"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
Medal No 31162,"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
Medal No 31163,"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
Medal No 31164,"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
Medal No 31165,"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [ ]:
summer.rename(columns={"Country": "country name"}, inplace=True)

In [301]:
summer.rename(columns = {'Country': 'country name'}, inplace = True)

In [302]:
summer

,Athlete,Year,City,Sport,Discipline,country name,Gender,Event,Medal
Medal No,,,,,,,,,
Medal No 1,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
Medal No 2,"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
Medal No 3,"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
Medal No 4,"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
Medal No 5,"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
Medal No 31161,"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
Medal No 31162,"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
Medal No 31163,"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
Medal No 31164,"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
Medal No 31165,"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [306]:
summer.columns.str.replace(' ','_', regex = False)

Index(['Athlete', 'Year', 'City', 'Sport', 'Discipline', 'country_name',
       'Gender', 'Event', 'Medal'],
      dtype='object')

In [305]:
summer

,Athlete,Year,City,Sport,Discipline,country name,Gender,Event,Medal
Medal No,,,,,,,,,
Medal No 1,"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
Medal No 2,"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
Medal No 3,"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
Medal No 4,"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
Medal No 5,"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
Medal No 31161,"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
Medal No 31162,"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
Medal No 31163,"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
Medal No 31164,"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
Medal No 31165,"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [310]:
#Data Frame Basics 2

#Data Frame Basisc2

In [309]:
###Data Frame Basisc2

In [311]:
import pandas as pd

In [312]:
titanic = pd.read_csv('titanic.csv')

In [313]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [314]:
titanic.sex.head()

0      male
1    female
2    female
3    female
4      male
Name: sex, dtype: object

In [316]:
titanic[(titanic.sex == 'male') & (titanic.age >70)]

     survived  pclass   sex   age  sibsp  parch     fare embarked deck
96          0       1  male  71.0      0      0  34.6542        C    A
116         0       3  male  70.5      0      0   7.7500        Q  NaN
493         0       1  male  71.0      0      0  49.5042        C  NaN
630         1       1  male  80.0      0      0  30.0000        S    A
851         0       3  male  74.0      0      0   7.7750        S  NaN

In [318]:
titanic.loc[(titanic.sex == 'male'), 'survived']

0      0
4      0
5      0
6      0
7      0
      ..
883    0
884    0
886    0
889    1
890    0
Name: survived, Length: 577, dtype: int64

In [322]:
titanic.iloc[5:45,4]

5     0
6     0
7     3
8     0
9     1
10    1
11    0
12    0
13    1
14    0
15    0
16    4
17    0
18    1
19    0
20    0
21    0
22    0
23    0
24    3
25    1
26    0
27    3
28    0
29    0
30    0
31    1
32    0
33    0
34    1
35    1
36    0
37    0
38    2
39    1
40    1
41    1
42    0
43    1
44    0
Name: sibsp, dtype: int64

In [323]:
mask1 = titanic.sex == 'male'

In [324]:
mask1

0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Name: sex, Length: 891, dtype: bool

In [332]:
titanic.loc[mask1,'survived']

0      0
4      0
5      0
6      0
7      0
      ..
883    0
884    0
886    0
889    1
890    0
Name: survived, Length: 577, dtype: int64

In [334]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      203 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [338]:
titanic[mask1].survived.count()

577

In [340]:
titanic.dtypes

survived      int64
pclass        int64
sex          object
age         float64
sibsp         int64
parch         int64
fare        float64
embarked     object
deck         object
dtype: object

In [341]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      203 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [344]:

titanic.loc[:, titanic.dtypes == 'int64']

     survived  pclass  sibsp  parch
0           0       3      1      0
1           1       1      1      0
2           1       3      0      0
3           1       1      1      0
4           0       3      0      0
..        ...     ...    ...    ...
886         0       2      0      0
887         1       1      0      0
888         0       3      1      2
889         1       1      0      0
890         0       3      0      0

[891 rows x 4 columns]

In [351]:
summer[summer.Year.between(1990,2010, inclusive = 'both')].size

86571

In [355]:
titanic['Zero'] = 0

In [356]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck  Zero
0         0       3    male  22.0      1      0   7.2500        S  NaN     0
1         1       1  female  38.0      1      0  71.2833        C    C     0
2         1       3  female  26.0      0      0   7.9250        S  NaN     0
3         1       1  female  35.0      1      0  53.1000        S    C     0
4         0       3    male  35.0      0      0   8.0500        S  NaN     0

In [357]:
titanic.Zero = titanic.pclass + 1

In [359]:
if titanic.pclass == 3:
    titanic.Zero = 'Less chances'
else: titanic.Zero = 'High Chances'

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [363]:
titanic.zero = IF titanic.pclass == 3: 'Less chances', 'High Chances'

SyntaxError: invalid syntax (2955376530.py, line 1)

In [365]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck  Zero
0         0       3    male  22.0      1      0   7.2500        S  NaN     4
1         1       1  female  38.0      1      0  71.2833        C    C     2
2         1       3  female  26.0      0      0   7.9250        S  NaN     4
3         1       1  female  35.0      1      0  53.1000        S    C     2
4         0       3    male  35.0      0      0   8.0500        S  NaN     4

In [369]:
titanic.insert(loc = 3, column = 'One1', value = titanic.Zero)

In [370]:
titanic

,survived,pclass,sex,One1,One,age,sibsp,parch,fare,embarked,deck,Zero
0,0,3,male,4,0,22.0,1,0,7.2500,S,NaN,4
1,1,1,female,2,0,38.0,1,0,71.2833,C,C,2
2,1,3,female,4,0,26.0,0,0,7.9250,S,NaN,4
3,1,1,female,2,0,35.0,1,0,53.1000,S,C,2
4,0,3,male,4,0,35.0,0,0,8.0500,S,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,3,0,27.0,0,0,13.0000,S,NaN,3
887,1,1,female,2,0,19.0,0,0,30.0000,S,B,2
888,0,3,female,4,0,NaN,1,2,23.4500,S,NaN,4
889,1,1,male,2,0,26.0,0,0,30.0000,C,C,2
890,0,3,male,4,0,32.0,0,0,7.7500,Q,NaN,4

In [371]:
titanic.drop(columns = ['Zero','One','One1'], inplace = True)

In [372]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [373]:
Creating Data from SCratch

SyntaxError: invalid syntax (184959082.py, line 1)

In [374]:
player = ["Lionel Messi", "Cristiano Ronaldo", "Neymar Junior", "Kylian Mbappe", "Manuel Neuer"]

In [375]:
nationality = ["Argentina", "Portugal", "Brasil", "France", "Germany"]

In [376]:
club = ["FC Barcelona", "Juventus FC", "Paris SG", "Paris SG", "FC Bayern" ]

In [377]:
world_champion = [False, False, False, True, True]

In [378]:
height = [1.70, 1.87, 1.75, 1.78, 1.93]

In [381]:
goals = [45, 44, 28, 21, 0]
dic = {"Player":player, "Nationality":nationality, "Club":club, 
        "World_Champion":world_champion, "Height":height, "Goals_2018":goals
       }

In [382]:
df = pd.DataFrame(dic)

In [383]:
df

,Player,Nationality,Club,World_Champion,Height,Goals_2018
0,Lionel Messi,Argentina,FC Barcelona,False,1.70,45
1,Cristiano Ronaldo,Portugal,Juventus FC,False,1.87,44
2,Neymar Junior,Brasil,Paris SG,False,1.75,28
3,Kylian Mbappe,France,Paris SG,True,1.78,21
4,Manuel Neuer,Germany,FC Bayern,True,1.93,0

In [384]:
df.set_index('Player', inplace = True)

In [386]:
values = [['Prateek','Chawla',33],['Navya','Chawla',2]]

In [387]:
columns = ['First Name', 'Last Name', 'Age']

In [388]:
index = ['Person 1', 'Person 2']

In [391]:
df = pd.DataFrame(data = values, columns = columns, index = index)

In [392]:
df

         First Name Last Name  Age
Person 1    Prateek    Chawla   33
Person 2      Navya    Chawla    2

In [394]:
players = pd.read_csv('players.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'players.csv'

In [395]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [396]:
# Manipulating Values in DataFrame

In [397]:
titanic

     survived  pclass     sex   age  sibsp  parch     fare embarked deck
0           0       3    male  22.0      1      0   7.2500        S  NaN
1           1       1  female  38.0      1      0  71.2833        C    C
2           1       3  female  26.0      0      0   7.9250        S  NaN
3           1       1  female  35.0      1      0  53.1000        S    C
4           0       3    male  35.0      0      0   8.0500        S  NaN
..        ...     ...     ...   ...    ...    ...      ...      ...  ...
886         0       2    male  27.0      0      0  13.0000        S  NaN
887         1       1  female  19.0      0      0  30.0000        S    B
888         0       3  female   NaN      1      2  23.4500        S  NaN
889         1       1    male  26.0      0      0  30.0000        C    C
890         0       3    male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [400]:
titanic.loc[1,'sex'] = 'Napunsak'

In [401]:
titanic

     survived  pclass       sex   age  sibsp  parch     fare embarked deck
0          10      10        10  10.0     10     10  10.0000       10   10
1           1       1  Napunsak  38.0      1      0  71.2833        C    C
2           1       3    female  26.0      0      0   7.9250        S  NaN
3           1       1    female  35.0      1      0  53.1000        S    C
4           0       3      male  35.0      0      0   8.0500        S  NaN
..        ...     ...       ...   ...    ...    ...      ...      ...  ...
886         0       2      male  27.0      0      0  13.0000        S  NaN
887         1       1    female  19.0      0      0  30.0000        S    B
888         0       3    female   NaN      1      2  23.4500        S  NaN
889         1       1      male  26.0      0      0  30.0000        C    C
890         0       3      male  32.0      0      0   7.7500        Q  NaN

[891 rows x 9 columns]

In [402]:
titanic['Zero'] = 0

In [403]:
titanic.Zero[titanic.pclass == 3] = 'Less Chances'

C:\Users\Mehak Chawla\AppData\Local\Temp\ipykernel_35928\2060829113.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  titanic.Zero[titanic.pclass == 3] = 'Less Chances'
C:\Users\Mehak Chawla\AppData\Local\Temp\ipykernel_35928\2060829113.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic.Zero[titanic.pclass == 3] = 'Less Chances'
C:\Users\Mehak Chawla\AppData\Local\Temp\ipykernel_35928\2060829113.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Less Chances' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  titanic.Zero[titanic.pclass == 3] = 'Less Chances'

In [408]:
titanic.Zero.unique()

array([0, 'Less Chances'], dtype=object)

In [ ]:
titanic.loc[3:,'Zero'] == 'Less Chances']

C:\Users\Mehak Chawla\AppData\Local\Temp\ipykernel_35928\1534222921.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  titanic[titanic.loc[3:,'Zero'] == 'Less Chances']

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [416]:
titanic.loc[0,'age'] = 99

In [417]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck,Zero
0,10,10,10,99.0,10,10,10.0000,10,10,0
1,1,1,Napunsak,38.0,1,0,71.2833,C,C,0
2,1,3,female,26.0,0,0,7.9250,S,NaN,Less Chances
3,1,1,female,35.0,1,0,53.1000,S,C,0
4,0,3,male,35.0,0,0,8.0500,S,NaN,Less Chances
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,NaN,0
887,1,1,female,19.0,0,0,30.0000,S,B,0
888,0,3,female,NaN,1,2,23.4500,S,NaN,Less Chances
889,1,1,male,26.0,0,0,30.0000,C,C,0
890,0,3,male,32.0,0,0,7.7500,Q,NaN,Less Chances

In [418]:
slice1 = titanic[['sex','age']]

In [428]:
slice1[1,'sex'] = 999999

C:\Users\Mehak Chawla\AppData\Local\Temp\ipykernel_35928\3773651665.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  slice1[1,'sex'] = 999999

In [420]:
slice1

          sex     age
0          10    99.0
1    Napunsak    38.0
2      female  9999.0
3      female    35.0
4        male    35.0
..        ...     ...
886      male    27.0
887    female    19.0
888    female     NaN
889      male    26.0
890      male    32.0

[891 rows x 2 columns]

In [429]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck,Zero
0,10,10,10,99.0,10,10,10.0000,10,10,0
1,1,1,Napunsak,7000.0,1,0,71.2833,C,C,0
2,1,3,female,26.0,0,0,7.9250,S,NaN,Less Chances
3,1,1,female,35.0,1,0,53.1000,S,C,0
4,0,3,male,35.0,0,0,8.0500,S,NaN,Less Chances
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,NaN,0
887,1,1,female,19.0,0,0,30.0000,S,B,0
888,0,3,female,NaN,1,2,23.4500,S,NaN,Less Chances
889,1,1,male,26.0,0,0,30.0000,C,C,0
890,0,3,male,32.0,0,0,7.7500,Q,NaN,Less Chances

In [422]:
age = titanic['age']

In [424]:
age._is_view

True

In [425]:
age._is_copy

In [426]:
age[1] = 7000

C:\Users\Mehak Chawla\AppData\Local\Temp\ipykernel_35928\3909448776.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  age[1] = 7000

In [427]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck,Zero
0,10,10,10,99.0,10,10,10.0000,10,10,0
1,1,1,Napunsak,7000.0,1,0,71.2833,C,C,0
2,1,3,female,26.0,0,0,7.9250,S,NaN,Less Chances
3,1,1,female,35.0,1,0,53.1000,S,C,0
4,0,3,male,35.0,0,0,8.0500,S,NaN,Less Chances
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,NaN,0
887,1,1,female,19.0,0,0,30.0000,S,B,0
888,0,3,female,NaN,1,2,23.4500,S,NaN,Less Chances
889,1,1,male,26.0,0,0,30.0000,C,C,0
890,0,3,male,32.0,0,0,7.7500,Q,NaN,Less Chances

In [430]:
import pandas as pd

In [432]:
titanic.age.sort_values(ascending = False)

1      7000.0
0        99.0
630      80.0
851      74.0
96       71.0
        ...
859       NaN
863       NaN
868       NaN
878       NaN
888       NaN
Name: age, Length: 891, dtype: float64

In [441]:
titanic.sort_values(by = 'parch', na_position = 'last', inplace = True)

In [442]:
titanic.sex.unique()

array(['male', 'female', 'Napunsak', 10], dtype=object)

In [450]:
sales = pd.Series([15, 32, 45, 21, -1, 0, 0],  index = ["Mo", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])

In [451]:
sales.rank(ascending = False, method = 'dense' )

Mo     4.0
Tue    2.0
Wed    1.0
Thu    3.0
Fri    6.0
Sat    5.0
Sun    5.0
dtype: float64

In [452]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck,Zero
890,0,3,male,32.0,0,0,7.7500,Q,NaN,Less Chances
503,0,3,female,37.0,0,0,9.5875,S,NaN,Less Chances
504,1,1,female,16.0,0,0,86.5000,S,B,0
505,0,1,male,18.0,1,0,108.9000,C,C,0
507,1,1,male,NaN,0,0,26.5500,S,NaN,0
...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,NaN,Less Chances
25,1,3,female,38.0,1,5,31.3875,S,NaN,Less Chances
13,0,3,male,39.0,1,5,31.2750,S,NaN,Less Chances
678,0,3,female,43.0,1,6,46.9000,S,NaN,Less Chances
0,10,10,10,99.0,10,10,10.0000,10,10,0

In [453]:
titanic.fare.rank(ascending = False, method = 'min')

890    753.0
503    562.0
504     64.0
505     50.0
507    270.0
       ...
885    244.0
25     212.0
13     216.0
678    166.0
0      556.0
Name: fare, Length: 891, dtype: float64

In [455]:
titanic.sort_values('fare', ascending = False)[titanic.sex == 'male']

C:\Users\Mehak Chawla\AppData\Local\Temp\ipykernel_35928\4121723669.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  titanic.sort_values('fare', ascending = False)[titanic.sex == 'male']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck,Zero
679,1,1,male,36.0,0,1,512.3292,C,B,0
737,1,1,male,35.0,0,0,512.3292,C,B,0
27,0,1,male,19.0,3,2,263.0000,S,C,0
438,0,1,male,64.0,1,4,263.0000,S,C,0
118,0,1,male,24.0,0,1,247.5208,C,B,0
...,...,...,...,...,...,...,...,...,...,...
597,0,3,male,49.0,0,0,0.0000,S,NaN,Less Chances
732,0,2,male,NaN,0,0,0.0000,S,NaN,0
822,0,1,male,38.0,0,0,0.0000,S,NaN,0
633,0,1,male,NaN,0,0,0.0000,S,NaN,0
674,0,2,male,NaN,0,0,0.0000,S,NaN,0

In [456]:
titanic.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [457]:
titanic.age.unique()

array([3.20e+01, 3.70e+01, 1.60e+01, 1.80e+01,      nan, 2.80e+01,
       2.60e+01, 2.90e+01, 3.60e+01, 5.40e+01, 2.40e+01, 4.70e+01,
       3.40e+01, 3.00e+01, 2.20e+01, 2.10e+01, 2.30e+01, 5.00e+01,
       6.30e+01, 2.50e+01, 3.50e+01, 5.80e+01, 5.50e+01, 7.10e+01,
       1.70e+01, 4.05e+01, 4.00e+01, 1.90e+01, 6.20e+01, 5.30e+01,
       3.90e+01, 4.80e+01, 1.50e+01, 4.50e+01, 6.40e+01, 2.70e+01,
       4.60e+01, 2.00e+01, 5.10e+01, 3.30e+01, 4.40e+01, 3.10e+01,
       4.20e+01, 3.45e+01, 4.90e+01, 6.50e+01, 3.80e+01, 5.60e+01,
       5.20e+01, 1.10e+01, 2.85e+01, 5.00e+00, 1.30e+01, 4.10e+01,
       3.05e+01, 5.70e+01, 6.00e+01, 4.30e+01, 6.10e+01, 8.00e+01,
       7.00e+01, 2.45e+01, 1.45e+01, 7.05e+01, 3.25e+01, 1.20e+01,
       5.55e+01, 4.55e+01, 6.60e+01, 1.40e+01, 7.00e+03, 5.90e+01,
       7.40e+01, 2.35e+01, 2.05e+01, 3.00e+00, 6.00e+00, 2.00e+00,
       7.00e+00, 6.70e-01, 8.00e+00, 4.00e+00, 4.20e-01, 1.00e+00,
       8.30e-01, 9.00e+00, 7.50e-01, 1.00e+01, 9.20e-01, 3.65e+01,
       9.90e+01])

In [458]:
titanic.age.nunique()

90

In [461]:
titanic.fare.idxmin()

481

In [463]:
titanic.describe(include = 'all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck,Zero
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,204,891
unique,NaN,NaN,4,NaN,NaN,NaN,NaN,4,8,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,C,Less Chances
freq,NaN,NaN,576,NaN,NaN,NaN,NaN,643,59,490
mean,0.395062,2.316498,NaN,39.557661,0.533109,0.392817,32.207294,NaN,NaN,NaN
std,0.583421,0.874577,NaN,261.270043,1.147432,0.867978,49.691962,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.925000,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.750000,1.000000,0.000000,31.000000,NaN,NaN,NaN
max,10.000000,10.000000,NaN,7000.000000,10.000000,10.000000,512.329200,NaN,NaN,NaN

In [464]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 890 to 0
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      204 non-null    object
 9   Zero      891 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 108.9+ KB

In [466]:
titanic.count(axis = 1)

890     9
503     9
504    10
505    10
507     8
       ..
885     9
25      9
13      9
678     9
0      10
Length: 891, dtype: int64

In [470]:
titanic.age.mean(axis = 1)

ValueError: No axis named 1 for object type Series

In [471]:
titanic.mean(numeric_only = True)

survived     0.395062
pclass       2.316498
age         39.557661
sibsp        0.533109
parch        0.392817
fare        32.207294
dtype: float64

In [473]:
titanic.fare.cumprod()

890    7.750000e+00
503    7.430313e+01
504    6.427220e+03
505    6.999243e+05
507    1.858299e+07
           ...
885    0.000000e+00
25     0.000000e+00
13     0.000000e+00
678    0.000000e+00
0      0.000000e+00
Name: fare, Length: 891, dtype: float64

In [476]:
titanic.corr(numeric_only = True)

          survived    pclass       age     sibsp     parch      fare
survived  1.000000 -0.106596  0.037976  0.124783  0.267873  0.205961
pclass   -0.106596  1.000000 -0.068655  0.157495  0.126146 -0.529292
age       0.037976 -0.068655  1.000000  0.005380 -0.023866  0.030985
sibsp     0.124783  0.157495  0.005380  1.000000  0.473168  0.149525
parch     0.267873  0.126146 -0.023866  0.473168  1.000000  0.194993
fare      0.205961 -0.529292  0.030985  0.149525  0.194993  1.000000

In [477]:
titanic.median(numeric_only = True)

survived     0.0000
pclass       3.0000
age         28.0000
sibsp        0.0000
parch        0.0000
fare        14.4542
dtype: float64

In [482]:
titanic.agg(['median'], numeric_only = True)

TypeError: Series.median does not allow numeric_only=True with non-numeric dtypes.

In [480]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 890 to 0
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   deck      204 non-null    object
 9   Zero      891 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 108.9+ KB

In [487]:
titanic.select_dtypes('number').agg(['mean','median','max','min','std','var','count'])

,survived,pclass,age,sibsp,parch,fare
mean,0.395062,2.316498,39.557661,0.533109,0.392817,32.207294
median,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
max,10.000000,10.000000,7000.000000,10.000000,10.000000,512.329200
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
std,0.583421,0.874577,261.270043,1.147432,0.867978,49.691962
var,0.340380,0.764885,68262.035302,1.316599,0.753387,2469.291122
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000

In [13]:
sales = pd.read_csv('sales.csv', index_col = 0)

In [2]:
import pandas as pd

In [14]:
sales

        Mon  Tue  Wed   Thu  Fri
Steven   34   27   15   NaN   33
Mike     45    9   74  87.0   12
Andi     17   33   54   8.0   29
Paul     87   67   27  45.0    7

In [12]:
sales.set_index('0', inplace = True)

KeyError: "None of ['0'] are in the columns"

In [7]:
sales

            Mon  Tue  Wed   Thu  Fri
Unnamed: 0
Steven       34   27   15   NaN   33
Mike         45    9   74  87.0   12
Andi         17   33   54   8.0   29
Paul         87   67   27  45.0    7

In [18]:
sales.rename(columns = {0: 'Month'}, inplace = True)

In [20]:
sales.index.rename('Name', inplace = True)

In [21]:
sales

        Mon  Tue  Wed   Thu  Fri
Name
Steven   34   27   15   NaN   33
Mike     45    9   74  87.0   12
Andi     17   33   54   8.0   29
Paul     87   67   27  45.0    7

In [33]:
def sample_function(x):
    return x**3

In [38]:
sales.apply(sample_function,axis = 1,inplace = True)

TypeError: sample_function() got an unexpected keyword argument 'inplace'

In [37]:
sales.fillna(sales.mean(), inplace = True)

In [36]:
sales

        Mon  Tue  Wed        Thu  Fri
Name
Steven   34   27   15  46.666667   33
Mike     45    9   74  87.000000   12
Andi     17   33   54   8.000000   29
Paul     87   67   27  45.000000    7